name: Container Image CI

on: 
  push:
    branches:
      - 'main'

jobs:
  Docker-Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2 
    
      -
        name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      -
        name: Build and Push Base
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:base"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/base-focal:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/base-focal:latest
          cache-to: type=inline
      
      -
        name: Build and Push Conda
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:conda"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/focal-conda:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/focal-conda:latest
          cache-to: type=inline